#!/usr/bin/env python3
import sys, os
import argparse
from omegaconf import OmegaConf

def SentencePieceTrain(config, text, model):
    config = OmegaConf.load(config)['sentencepiece']
    option_string = (
        F' --input={text} '
        F' --model_prefix={model} '
        ' '.join([ F'--{k}={v}' for k,v in config.items()])
    )
    spm.SentencePieceTrainer.Train(option_string)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--backend', choices = ['sentencepiece'], default = 'sentencepiece')
    parser.add_argument('--config', type = str)
    parser.add_argument('--text', type = str)
    parser.add_argument('--model', type = str)
    args = parser.parse_args()
    print(args, file=sys.stderr)

    if args.backend == 'sentencepiece':
        import sentencepiece as spm
        # https://colab.research.google.com/github/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
        if not os.path.isdir(os.path.dirname(args.model)):
            os.mkdir(os.path.dirname(args.model))
        SentencePieceTrain(args.config, args.text, args.model)
    else:
        raise NotImplementedError(F'Unsupported tokenizer backend: {args.backend}')
