#!/usr/bin/env python3
import os, argparse
from omegaconf import OmegaConf

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--backend', choices = ['sentencepiece'], default = 'sentencepiece')
    parser.add_argument('config', type = str)
    parser.add_argument('text', type = str)
    parser.add_argument('model_dir', type = str)
    args = parser.parse_args()
    print(args)

    if not os.path.isdir(args.model_dir):
        os.mkdir(args.model_dir)

    if args.backend == 'sentencepiece':
        import sentencepiece as spm

        options = (
            F'--input={args.text} '
            F'--model_prefix={os.path.join(args.model_dir, "tokenizer")} '
        )
        spm_cfg = OmegaConf.load(args.config)['sentencepiece']
        for e in spm_cfg:
            options += F'--{e}={spm_cfg[e]} '

        spm.SentencePieceTrainer.train(options)

    else:
        raise NotImplementedError(F'Unsupported tokenizer backend: {args.backend}')
