#!/usr/bin/env python3

import argparse, os, sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('operation', type = str, choices = ['stt', 'lm', 'tokenizer'])
    args = parser.parse_args()

    pmap = {
        'stt': 'stt_train',
        'lm': 'lm_train',
        'tokenizer': 'tokenizer_train',
    }

    cmd = f'pkill -f {pmap[args.operation]}'
    print(cmd, file = sys.stderr)
    os.system(cmd)

