#!/usr/bin/env python3

import sys, os, argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', type = int, default = 2)
    parser.add_argument('--order', type = int, default = 6)
    parser.add_argument('iarpa', type = str)
    parser.add_argument('threshold', type = float)
    parser.add_argument('oarpa', type = str)
    args = parser.parse_args()

    cmd = f'ngram -debug {args.debug} -order {args.order} -lm {args.iarpa} -prune {args.threshold} -write-lm {args.oarpa}'
    print(cmd, file = sys.stderr)
    os.system(cmd)

