#!/usr/bin/env python3

import sys, os, argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', action='store_true', help = 'Do not wrap the input in <s> and </s>.')
    parser.add_argument('--model', type = str, required = True)
    parser.add_argument('--text', type = str, required = True)
    args = parser.parse_args()

    cmd = f'cat {args.text} | query {"-n" if args.n else ""} {args.model}'
    print(cmd, file = sys.stderr)
    os.system(cmd)

