#!/usr/bin/env python3

import sys, os, argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', type = int, default = 2)
    parser.add_argument('--order', type = int, default = 6)
    parser.add_argument('--imodel', type = str, required = True)
    parser.add_argument('--threshold', type = float, required = True)
    parser.add_argument('--omodel', type = str, required = True)
    args = parser.parse_args()

    cmd = f'ngram -debug {args.debug} -order {args.order} -lm {args.imodel} -prune {args.threshold} -write-lm {args.omodel}'
    print(cmd, file = sys.stderr)
    os.system(cmd)

