#!/usr/bin/env python3
# coding = utf8
#
# Copyright (c) 2021 Jiayu DU
# All rights reserved.

import sys, argparse
from pysio import stt

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('-c', '--config', type = str, required = True)
    parser.add_argument('-o', 'dir', type = str, required = True)

    args = parser.parse_args()
    print(args, file=sys.stderr)

    stt.recognize(args.config, args.dir)

