#!/usr/bin/env python3
# coding = utf8

import sys, os, argparse

if __name__ == '__main__':
    DESCRIPTION = '''
    e.g:
        ops/text_norm --nj 10 --input i.txt --output o.txt
    '''
    parser = argparse.ArgumentParser(description = DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--nj', type = int, default = 1)
    parser.add_argument('--opts', type = str, default = "--to_banjiao --to_upper --check_chars --remove_space")

    parser.add_argument('--input', type = str, required = True)
    parser.add_argument('--output', type = str, required = True)
    args = parser.parse_args()
    print(args, file=sys.stderr)

    if args.nj == 1:

        os.system(f'ops/cn_tn.py {args.opts} args.input args.output')

    else:
        import glob

        wdir = args.output + '.dir'
        os.makedirs(wdir, exist_ok = True)

        print(f'Partitioning input {args.input} into {wdir} ...', file = sys.stderr)
        os.system(f'split -n l/{args.nj} {args.input} {os.path.join(wdir, "split.")}')

        print('Tokenizing all partitions ...', file = sys.stderr)
        partitions = glob.glob(os.path.join(wdir, 'split.*'))

        cmds = os.path.join(wdir, 'cmds')
        with open(cmds, 'w+') as f:
            for x in partitions:
                out = os.path.join(wdir, os.path.basename(x).replace('split', 'out'))
                log = os.path.join(wdir, os.path.basename(x).replace('split', 'log'))
                print(f'ops/cn_tn.py {args.opts} {x} {out} >& {log}', file = f)
        os.system(f'ops/run_para --nj {args.nj} {cmds}')

        print('Merging results of all partitions ...', file = sys.stderr)
        os.system(f'cat {os.path.join(wdir, "out.*")} > {args.output}')

