#!/usr/bin/env bash

if [ $# -ne 4 ]; then
    echo "tokenize nj tokenizer input.txt output_prefix"
    exit 1;
fi

nj=$1
tokenizer=$2
text=$3
prefix=$4

mkdir -p `dirname $prefix`

echo "$0: Partitioning input text"
split -n l/${nj} $text ${prefix}_

echo "$0: tokenizing all partitions in parallel"
for f in `ls ${prefix}_*`; do
    ops/tokenizer_encode --model $tokenizer --input $f --output ${f}_out >& ${f}.log &
done
wait

echo "$0: Merging all partition results"
cat ${prefix}_*_out > ${prefix}.txt

echo "$0: done"

