#!/usr/bin/env python3
# Copyright (c) 2021 Jiayu DU
# All rights reserved.

import sys, os
import argparse
from omegaconf import OmegaConf
import sentencepiece as spm

def SentencePieceTrain(config, text, model):
    # https://colab.research.google.com/github/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
    dst = os.path.dirname(args.model)
    if dst and not os.path.isdir(dst):
        os.makedirs(dst, exist_ok = True)

    config = OmegaConf.load(config)['sentencepiece']
    trainer_spec = (
        F' --input={text} '
        F' --model_prefix={model} '
        ' '.join([ F'--{k}={v}' for k,v in config.items()])
    )
    spm.SentencePieceTrainer.Train(trainer_spec)
    '''
    To check vocab ~ id list:
      https://github.com/google/sentencepiece/issues/328

    >>> import sentencepiece as spm
    >>> sp = spm.SentencePieceProcessor()
    >>> sp.load('test_model.model')
    True
    >>> vocabs = [[sp.id_to_piece(id), id] for id in range(sp.get_piece_size())]
    >>> vocabs
    [['<unk>', 0], ['<s>', 1], ['</s>', 2], ['\r', 3], ['▁', 4], [',', 5], ...
    
    '''


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type = str, required = True)
    parser.add_argument('--input', type = str, required = True, help='text, one sentence per line.')
    parser.add_argument('--model', type = str, required = True)
    args = parser.parse_args()
    print(args, file=sys.stderr)

    SentencePieceTrain(args.config, args.input, args.model)
