#!/usr/bin/env python3
# Copyright (c) 2021 Jiayu DU
# All rights reserved.

import sys, os
import argparse
from omegaconf import OmegaConf

def SentencePieceTrain(config, text, language, model):
    import sentencepiece as spm
    # https://colab.research.google.com/github/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
    
    dst = os.path.dirname(args.model)
    if not os.path.isdir(dst):
        os.makedirs(dst, exist_ok = True)

    config = OmegaConf.load(config)['sentencepiece'][language]
    trainer_spec = (
        F' --input={text} '
        F' --model_prefix={model} '
        ' '.join([ F'--{k}={v}' for k,v in config.items()])
    )
    spm.SentencePieceTrainer.Train(trainer_spec)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--backend', choices = ['sentencepiece'], default = 'sentencepiece')
    parser.add_argument('--language', choices = ['EN', 'ZH'], default = 'ZH')
    parser.add_argument('--config', type = str, required = True)
    parser.add_argument('--input', type = str, required = True)
    parser.add_argument('--model', type = str, required = True)
    args = parser.parse_args()
    print(args, file=sys.stderr)

    if args.backend == 'sentencepiece':
        SentencePieceTrain(args.config, args.input, args.language, args.model)
    else:
        raise NotImplementedError(F'Unsupported tokenizer backend: {args.backend}')
